services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: game-live
      POSTGRES_USER: game-live
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  stream-server:
    image: bluenviron/mediamtx
    environment:
      MTX_PROTOCOLS: tcp
      MTX_WEBRTCADDITIONALHOSTS: host.docker.internal
      MTX_EXTERNALAUTHENTICATIONURL: "http://host.docker.internal:5101/api/connection/authenticate"
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
    command: server /data

  keycloak-postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: user
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - keycloak-postgres
    command: start-dev