services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: game-live
      POSTGRES_USER: game-live
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  stream-server:
    image: game-live/stream-server
    build:
      context: ./mediamtx
      args:
        TARGETARCH: amd64
        VERSION: v1.4.2
    volumes:
      - "./mediamtx/mediamtx.development.yaml:/app/mediamtx.yml"
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"

  cache:
    image: redis
    ports:
      - "6379:6379"

  message-queue:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  object-storage:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
    command: server /data

  oidc-provider-db:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  oidc-provider:
    image: quay.io/keycloak/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: oidc-provider-db
      DB_DATABASE: keycloak
      DB_USER: user
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - "./keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json"
    depends_on:
      - oidc-provider-db
    command: start-dev --import-realm