// <auto-generated />
using System;
using GameLiveServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameLiveServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240123112407_AddChatSettingsToStream")]
    partial class AddChatSettingsToStream
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameLiveServer.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarContentType")
                        .HasColumnType("text");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("GameLiveServer.Models.BroadcasterViewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BroadcasterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ViewerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BroadcasterId");

                    b.HasIndex("ViewerId");

                    b.HasIndex("ConnectionId", "ViewerId", "BroadcasterId")
                        .IsUnique();

                    b.ToTable("BroadcasterViewers");
                });

            modelBuilder.Entity("GameLiveServer.Models.LiveStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ChatEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ChatFollowersOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Live")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServerUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("StreamKey")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailContentType")
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("StreamKey")
                        .IsUnique();

                    b.ToTable("LiveStreams");
                });

            modelBuilder.Entity("GameLiveServer.Models.BroadcasterViewer", b =>
                {
                    b.HasOne("GameLiveServer.Models.AppUser", "Broadcaster")
                        .WithMany("Viewers")
                        .HasForeignKey("BroadcasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLiveServer.Models.AppUser", "Viewer")
                        .WithMany("Broadcasters")
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broadcaster");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("GameLiveServer.Models.LiveStream", b =>
                {
                    b.HasOne("GameLiveServer.Models.AppUser", "AppUser")
                        .WithOne("LiveStream")
                        .HasForeignKey("GameLiveServer.Models.LiveStream", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("GameLiveServer.Models.AppUser", b =>
                {
                    b.Navigation("Broadcasters");

                    b.Navigation("LiveStream")
                        .IsRequired();

                    b.Navigation("Viewers");
                });
#pragma warning restore 612, 618
        }
    }
}
